name: QA

on: [push]

jobs:
  # Set the job key. The key is displayed as the job name
  # When a job name is not provided
  tsc-and-linters:
     runs-on: ubuntu-latest
     steps:
       # Checks out a copy of your repository on the ubuntu-latest maching
      - name: Checkout code
        uses: actions/checkout@v2      

      - name: Install deps
        run: |
          npm ci
      - name: Run tsc
        run: |
          npm run check-types
      - name: Run lint
        run: |
          npm run lint
          git diff --exit-code ./src
